"use client";

// Importing necessary modules and components
import { ThemeProvider as NextThemesProvider } from "next-themes"; // For theme management (dark/light mode)
import Header from "@/components/custom/Header"; // Custom header component
import { MassageContext } from "@/context/MassageContext"; // Context to manage massage-related state
import { useEffect, useState } from "react"; // React hooks to manage state and side effects
import { UserContext } from "@/context/UserContext"; // Context to manage user details
import { GoogleOAuthProvider } from "@react-oauth/google"; // Provider for Google OAuth authentication
import { useConvex } from "convex/react"; // Convex hook to interact with the backend
import { api } from "@/convex/_generated/api"; // API routes generated by Convex
import { GetUser } from "@/convex/users"; // Function to fetch user data from Convex

const Provider = ({ children }) => {
  // State to manage massage and user details
  const [massage, setMassage] = useState([]);
  const [userDetail, setUserDetail] = useState();

  // Convex hook to interact with the Convex backend
  const convex = useConvex();

  // Effect hook to check if the user is authenticated on component mount
  useEffect(() => {
    isAuthenticated(); // Function to verify authentication
  }, []); // Empty dependency array to ensure it runs once on mount

  // Function to check if the user is authenticated
  const isAuthenticated = async () => {
    if (typeof window !== "undefined") {
      // Check if we're on the client-side (window is available only in the browser)
      const user = JSON.parse(localStorage.getItem("user")); // Retrieve user details from localStorage
      console.log("User from localStorage:", user); // Debug log

      // Query Convex to fetch user details from the backend using the email
      const result = await convex.query(api.users.GetUser, {
        email: user?.email, // Pass email to the query to get the user data
      });

      // Set the user details in the state
      setUserDetail(result);
      console.log("Convex Query Result:", result); // Debug log
    }
  };

  return (
    // Google OAuth provider to handle authentication
    <GoogleOAuthProvider
      clientId={process.env.NEXT_PUBLIC_GOOGLE_AUTH_CLIENT_ID_KEY} // Use the Google OAuth client ID from environment variables
    >
      {/* User context provider to make user details available throughout the app */}
      <UserContext.Provider value={{ userDetail, setUserDetail }}>
        {/* Massage context provider to share massage state across components */}
        <MassageContext.Provider value={{ massage, setMassage }}>
          {/* Theme provider to manage dark/light theme */}
          <NextThemesProvider
            attribute="class" // Apply theme as a class to the HTML element
            defaultTheme="dark" // Default theme set to dark
            enableSystem // Allow the system's theme preference to be used
            disableTransitionOnChange // Disable theme transition on change for smoother switching
          >
            <Header /> {/* Render the header component */}
            <div>{children}</div> {/* Render the children components */}
          </NextThemesProvider>
        </MassageContext.Provider>
      </UserContext.Provider>
    </GoogleOAuthProvider>
  );
};

export default Provider; // Export the provider component for use in the app
